name: CD Fake
on:
  workflow_dispatch:
jobs:
  deploy-fake:
    runs-on: ubuntu-latest
    environment: producao
    steps:
      - name: Fake de deploy em ambiente
        run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
